use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{identifiers::Identifiers, language::Language};

/// Describes a list of properties for various Card Data Models in alternate languages.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ForeignData {
    /// The foreign name on the face of the card.
    pub face_name: Option<String>,

    /// The foreign flavor text of the card.
    pub flavor_text: Option<String>,

    /// A list of identifiers associated to the card.
    pub identifiers: Option<Identifiers>,

    /// The foreign language of card.
    pub language: Language,

    /// The foreign multiverse identifier of the card. Use the `identifiers.multiverse_id` property.
    #[deprecated(since = "5.3.0", note = "Will be removed in 6.0.0")]
    pub multiverse_id: Option<u32>,

    /// The foreign name of the card.
    pub name: String,

    /// The foreign text ruling of the card.
    pub text: Option<String>,

    /// The foreign type of the card. Includes any supertypes and subtypes.
    #[serde(rename = "type")]
    pub card_type: Option<String>,

    /// The universal unique identifier (v5) generated by MTGJSON.
    pub uuid: Option<Uuid>,
}
