use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{identifiers::Identifiers, purchase_urls::PurchaseUrls};

/// Describes a purchasable product printing of a token, linking together the
/// faces of double-sided tokens.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TokenProduct {
    /// A list of identifiers associated to the product.
    pub identifiers: Identifiers,

    /// Links that navigate to websites where the product can be purchased.
    pub purchase_urls: PurchaseUrls,

    /// The token faces included in the product.
    pub token_parts: Vec<TokenPart>,
}

/// A single token face within a [`TokenProduct`].
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TokenPart {
    /// A list of attributes of the token face, such as its treatment.
    pub face_attribute: Option<Vec<String>>,

    /// The identifier of the face within the token.
    pub face_id: Option<String>,

    /// The name of the token face.
    pub face_name: Option<String>,

    /// The type of the token face.
    pub token_type: Option<String>,

    /// The universal unique identifier (v5) generated by MTGJSON.
    pub uuid: Option<Uuid>,
}
